### ISSUE TITLE
调整路径后无法编译

### ISSUE THREAD

**Issue by Halooooooo** [nolebase/nolebase#46]
首先这是一个非常好的项目，目前我准备推动使用他作为我们项目的操作手册及知识库，但是在调整文件目录的时候发现了如下报错：
执行 pnpm run build 后

`
build error:
Error: [vite]: Rollup failed to resolve import "assets/how-llm-works-aftermath-of-llm-video-1.mp4" from "C:/Users/67357/IdeaProjects/nolebase/知识库/🤖 AI 人工智能/LLM 是如何工作的？.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/vite@5.2.8_@types+node@20.10.6_less@4.2.0/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67589:27)
    at onRollupWarning (file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/vite@5.2.8_@types+node@20.10.6_less@4.2.0/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67617:9)
    at onwarn (file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/vite@5.2.8_@types+node@20.10.6_less@4.2.0/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67321:13)
    at file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:18303:13
    at Object.logger [as onLog] (file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:19950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:18893:26)
    at file:///C:/Users/67357/IdeaProjects/nolebase/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:18851:26
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by nekomeowww** [comment]
谢谢你的提问。

> `Rollup failed to resolve import "assets/how-llm-works-aftermath-of-llm-video-1.mp4" from "C:/Users/67357/IdeaProjects/nolebase/知识库/🤖 AI 人工智能/LLM 是如何工作的？.md"`

这个报错的核心在于这句话，`C:/Users/67357/IdeaProjects/nolebase/知识库/🤖 AI 人工智能/LLM 是如何工作的？.md` 中引用的 `assets/how-llm-works-aftermath-of-llm-video-1.mp4` 找不到了。

- 你删除过 `C:/Users/67357/IdeaProjects/nolebase/知识库/🤖 AI 人工智能` 的 `assets` 目录对吗？
- 如果不想要报错，可以
  - 1. 连带着把 `笔记` 目录整个清空了，这样你可以自己从头开始打造自己的知识库。
  - 2. 去 `C:/Users/67357/IdeaProjects/nolebase/知识库/🤖 AI 人工智能/LLM 是如何工作的？.md` 这个文件中，找到 `assets/how-llm-works-aftermath-of-llm-video-1.mp4` 然后删除它就好了。
