### ISSUE TITLE
Could not resolve "./foo.webp" from "bar.md"

### ISSUE THREAD

**Issue by zhenqian168** [nolebase/nolebase#71]
build error:
RollupError: Could not resolve "./../../../_resources/v2-9b73c58ccd196f03a410d4ef00c8c_45eee3b981dc4cb18.webp" from "Content/知乎严选/PPT 演讲力：关键时刻，不要输在表达上_.md"
file: /vercel/path0/Content/知乎严选/PPT 演讲力：关键时刻，不要输在表达上_.md
    at getRollupError (file:///vercel/path0/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///vercel/path0/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19106:24)
    at file:///vercel/path0/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19066:26
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

![2024-10-11_191811](https://github.com/user-attachments/assets/6a18c242-0fbf-4bd5-ab23-bc9b66805dd0)

**Comment by nekomeowww** [comment]
请提供最小复现或给予我们更多的上下文信息（比如 Markdown 原文是如何引用图片的），或者图片是否位于 `resources/v2-9b73c58ccd196f03a410d4ef00c8c_45eee3b981dc4cb18.webp`。
